### PR TITLE
Project completed

### PR DESCRIPTION
**Pull request by webmarkyn**

### CODE REVIEW

**Review by uche-inyama — COMMENTED** [review]
## Pull Request under review by:  Inyama, Uchechukwu Henry

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi @webmarkyn, good job :smiley: 

### However, there are changes to implement

- [ ] First, your README.md file is **not detailed**. It should contain information such as:
     * A definition of this project
     * The authors of the project
     * Link to the **Clone**, you can use [Githack](https://raw.githack.com/) to get a link, by pasting the link of your html file from github on the field at **githack**
     * Also, you can provide a link to **Odin's project** for detailed information.

- [ ] There are no linter checks on this project, kindly include them and ensure it passes the error checks
Read through this [Link](https://github.com/microverseinc/linters-config/tree/master/css)

- [ ] This project has seperate the sections. Each section (video, comments, sidebar, navigation bar) should have it's own container. It can be implemented using the ```<section>``` **tag**

- [ ] This project is [Collaborative](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/) but you worked on it alone, **why?**
#### Kindly implement these changes, then submit another form for code review :+1: 

### Your project hasn't been approved :stop_sign:

**Comment by webmarkyn** [comment]
I did this project alone because I have no coding partner for now. I think I'm going to be repaired.
Also, I didn't quite understand what do you mean by separating sections, because I think I have separated all of them. But I changed some things.

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work @webmarkyn  :clap: . You fixed the linter issues :100: , however you still need to fix the following problems :arrow_down: 

- Add a more info to your readme file and make it more readable.
- run you html file through the [validator](https://validator.w3.org) and fix the errors

### And that's it, when finished, kindly resubmit another code review request :pray:

**Review by stratospherique — APPROVED** [review]
### Great work :clap: . You made all the necessary changes :100: . The project is approved :100: and you can merge to master :+1: :+1:

**Pull request merged**
